import split_event
import cv2
import numpy as np

DOOR_H = split_event.TemplateMatch("d/door_h.png")
DOOR_V = split_event.TemplateMatch("d/door_v.png")
DOOR_V_LONG = split_event.TemplateMatch("d/longdoor_v.png")
VARIA_FACE = split_event.TemplateMatch("d/varia.png")
DOOR_C = split_event.TemplateMatch("d/door_c.png")
FADE_BLACK = split_event.ColorMatch((0, 0, 0))


class Split(object):
    def __init__(self, name, split_event, sleep_time=1.9):
        self.name = name
        self.event = split_event
        self.sleep_time = sleep_time
        self.time = -1

    def reset(self):
        self.time = -1

    def skip(self):
        self.time = 0


route = [
    Split("Start", FADE_BLACK, 9),
    Split("Ceres Elevator", FADE_BLACK),
    Split("Falling Tiles", DOOR_C),
    Split("Magnet Stairs", DOOR_C),
    Split("Dead Scientist", DOOR_C),
    Split("58", FADE_BLACK, 9),
    Split("Ceres Ridley", FADE_BLACK),
    Split("58 Escape", DOOR_C),
    Split("Dead Scientist Escape", DOOR_C),
    Split("Magnet Stairs Escape", DOOR_C),
    Split("Falling Tiles Escape", FADE_BLACK, 6),
    Split("Ceres Escape", FADE_BLACK, 50),
    Split("Landing Site", DOOR_H),
    Split("Parlor", DOOR_V),
    Split("Moonfall Climb", DOOR_H),  #fast scrolling glitch the door tiles but it's still matched!
    Split("Pit", DOOR_H),
    Split("Elevator to Morphball", FADE_BLACK),
    Split("Morphball", DOOR_H),
    Split("Construction", DOOR_H),
    Split("First Missile", DOOR_H),
    Split("reConstruction", DOOR_H),
    Split("Morph Elevator", FADE_BLACK),
    Split("Elevator from Morphball", DOOR_H),
    Split("Pit Awake", DOOR_H),
    Split("Climb Awake", DOOR_V),
    Split("Parlor Awake", DOOR_H),
    Split("Flyway", DOOR_H),
    Split("Bomb Torizo", DOOR_H),
    Split("Flyway from Bomb", DOOR_H),
    Split("Alcatraz", DOOR_H),
    Split("Terminator", DOOR_H),
    Split("Green Pirates", DOOR_H),
    Split("Mushrooms", DOOR_H),
    Split("Green Brinstar Elevator", FADE_BLACK),
    Split("Green Brinstar Shaft", DOOR_H),
    Split("Early Supers", DOOR_H),
    Split("Green Shaft to Pink", DOOR_H),
    Split("Dachora", DOOR_H),
    Split("Big Pink", DOOR_H),
    Split("Green Hill", DOOR_H),
    Split("Noob Bridge", DOOR_H),
    Split("Red Tower", DOOR_H),
    Split("Bat", DOOR_H),
    Split("Below Spazer", DOOR_H),
    Split("Maridia Tube???", DOOR_H),
    Split("Warehouse Entrance", DOOR_H),
    Split("Hi Zeela", DOOR_V_LONG),
    Split("Hi Kihunters", DOOR_H),
    Split("Hi Baby Kraid", DOOR_H),
    Split("Hi Kraid Eye Door", FADE_BLACK),
    Split("Hi Kraid", FADE_BLACK),
    Split("Varia", VARIA_FACE),
    Split("Bye Kraid", DOOR_H),
    #Split("Bye Kraid Eye Door", DOOR_H),  # in the middle of kraid's room everything is black
    Split("Bye Baby Kraid", DOOR_H),
    Split("Bye Kihunters", DOOR_V_LONG),
    Split("Bye Zeela", DOOR_H),
    Split("Norfair Elevator", FADE_BLACK),
    Split("Business Center to HJ", DOOR_H),
    Split("HJ ETank", DOOR_H),
    Split("Hi Jump Boot", DOOR_H),
    Split("Skip Missile", DOOR_H),
    Split("Business Center", DOOR_H),
    Split("Cathedral Entrance", DOOR_H),
    Split("Cathedral", DOOR_H),
    Split("Rising Tide", DOOR_H),
    Split("Bubble Mountain to HJ", DOOR_H),
    Split("Bat Cave", DOOR_H),
    Split("Speed Booster Hall", DOOR_H),
    Split("Speed Booster", DOOR_H),
    Split("Speed Booster Escape", DOOR_H),
    Split("Bat Cave Escape", DOOR_H),
    Split("Bubble Mountain to WB", DOOR_H),
    Split("Single Chamber to WB", DOOR_H),
    Split("Double Chamber to WB", DOOR_H),
    Split("Wave Beam", DOOR_H),
    Split("Double Chamber", DOOR_H),
    Split("Single Chamber", DOOR_H),
    Split("Bubble Mountain", DOOR_H),
    Split("Upper Norfair Farming", DOOR_H),
    Split("Frog Speedway", DOOR_H),
    Split("Frog Savestation", DOOR_H),
    Split("Business Center to WS", FADE_BLACK),
    Split("Warehouse Entrance to WS", DOOR_H),
    Split("Maridia Tube to WS", DOOR_H),
    Split("Below Spazer Spark", DOOR_H),
    Split("Bat Spark", DOOR_H),
    Split("Red Tower Climb", DOOR_H),
    Split("Hellway", DOOR_H),
    Split("Caterpillar", DOOR_H),
    Split("Alpha Power Bomb", DOOR_H),
    Split("Caterpillar PB", FADE_BLACK),
    Split("Red Brinstar Elevator PB", DOOR_V),
    Split("Crateria Kihunter PB", DOOR_H),
    Split("The Moat", DOOR_H),  # **********
    Split("Ocean Fly", DOOR_H),
    Split("Wrecked Ship Entrance", DOOR_H),
    Split("WS Shaft Asleep", DOOR_V),
    Split("Basement Asleep", DOOR_H),
    Split("Phantoon", DOOR_H),
    Split("Basement Awake", DOOR_V),
    Split("WS Shaft Awake", DOOR_V),
    Split("Attic", DOOR_H),
    Split("Floating Platforms", DOOR_H),
    Split("Bowling Alley", DOOR_H),
    Split("Gravity", DOOR_H),
    Split("West Ocean", DOOR_H),
    Split("Moat to Maridia", DOOR_H),
    Split("Crateria Kihunter to Maridia", DOOR_V),
    Split("Elevator to Maridia", FADE_BLACK),
    Split("Caterpillar to Maridia", DOOR_H),
    Split("Hellway to Maridia", DOOR_H),
    Split("Red Tower Fall", DOOR_H),
    Split("Bat to Maridia", DOOR_H),
    Split("Bellow Spazer to Maridia", DOOR_H),
    Split("Tube", DOOR_V),
    Split("Main Street", DOOR_H),
    Split("Fish Tank", DOOR_V),
    Split("Everest", DOOR_H),
    Split("Crab Shaft", DOOR_H),
    Split("Aqueduct", DOOR_V),
    Split("Botwoon Hallway", DOOR_H),
    Split("Botwoon", DOOR_H),
    Split("Botwoon ETank", DOOR_H),
    Split("Halfie Climb", DOOR_H),
    Split("Colosseum", DOOR_H),
    Split("Draygon Eye Door", FADE_BLACK),
    Split("Draygon", DOOR_H),
    Split("Reverse Halfie", DOOR_H),
    Split("To Cac Alley", DOOR_H),
    Split("Cactus Alley", DOOR_H),  ##misssing dboost room
    Split("Butterfly", DOOR_H),
    Split("Plasma Spark", DOOR_H),
    Split("Kassiuz Climb", DOOR_H),
    Split("Puyo!", DOOR_H),
    Split("Plasma", DOOR_H),
    Split("Plasma Tutorial", DOOR_H),
    Split("Kassiuz Fall", DOOR_H),
    Split("Oasis", DOOR_H),
    Split("Sand Hall", DOOR_H),
    Split("Crab Hole Tunnel", DOOR_H),  # room too fast?
    Split("Crab Hole", DOOR_H),
    Split("East Tunnel", DOOR_H),
    Split("Norfair Elevator to Ice", FADE_BLACK),
    Split("Business Center to Ice", DOOR_H),
    Split("Ice Shutters", DOOR_H),
    Split("Ice Acid", DOOR_H),
    Split("Ice Snake", DOOR_H),
    Split("Ice Beam", DOOR_H),
    Split("Ice Snake down", DOOR_H),
    Split("Ice Acid Mockball", DOOR_H),
    Split("Ice Shutters Mockball", DOOR_H),
    Split("Business Center to LN", DOOR_H),
    Split("Frog Save to LN", DOOR_H),
    Split("Frog Speedway to LN", DOOR_H),
    Split("Farming Room to LN", DOOR_H),
    Split("Bubble Mountain to LN", DOOR_V),
    Split("Purple Shaft", DOOR_H),
    Split("Magdollite", DOOR_H),
    Split("Kronic Boost", DOOR_H),
    Split("Lava Dive", DOOR_H),
    Split("Lower Norfair Elevator", FADE_BLACK),
    Split("Main Hall", DOOR_H),
    Split("Fast Pillars Setup", DOOR_H),
    Split("Pillar", DOOR_H),
    Split("WRITG", DOOR_H),
    Split("Amphitheatre", DOOR_H),
    Split("Red Kihunter Shaft", DOOR_V),
    Split("WasteLand", DOOR_H),
    Split("Metal Pirates", DOOR_H),
    Split("Plowerhouse", DOOR_H),
    Split("Ridley's Farming", DOOR_H),
    Split("Ridley", DOOR_H),
    Split("Ridley Escape", DOOR_H),
    Split("Plowerhouse Escape", DOOR_H),
    Split("WasteLand Escape", DOOR_V),
    Split("Red Kihunter Shaft Climb", DOOR_H),
    Split("LN Fireflea", DOOR_H),
    Split("Spring Ball Maze", DOOR_H),
    Split("Three Muskateers", DOOR_H),
    Split("Single Chamber to Tourian", DOOR_H),
    Split("Bubble Mountain to Tourian", DOOR_H),
    Split("Farming Room to Tourian", DOOR_H),
    Split("Frog Speedway to Tourian", DOOR_H),
    Split("Frog Save to Tourian", DOOR_H),
    Split("Business Center to Tourian", FADE_BLACK),
    Split("Norfair Elevator to Tourian", DOOR_H),
    Split("Tube to Tourian", DOOR_V),
    Split("Main Street to Tourian", DOOR_H),
    Split("Fish Tank to Tourian", DOOR_V),
    Split("Everest to Tourian", DOOR_V),
    Split("Red Fish", DOOR_H),
    Split("Caterpillar Elevator", FADE_BLACK),
    Split("Red Brinstar Elevator", DOOR_V),
    Split("Crateria Kihunter to Tourian", DOOR_H),
    Split("Landing Site to Tourian", DOOR_H),
    Split("Parlor to Tourian", DOOR_H),
    Split("Terminator to Tourian", DOOR_H),
    Split("Green Pirates to Tourian", DOOR_H),
    Split("Statues Hallway", DOOR_H),
    Split("G4", FADE_BLACK),
    Split("Tourian Elevator", DOOR_H),
    Split("Metroid 1", DOOR_H),
    Split("Metroid 2", DOOR_H),
    Split("Metroid 3", DOOR_H),
    Split("Metroid 4", DOOR_V),
    Split("Blue Hopper", DOOR_H),
    Split("Dust Torizo", DOOR_H),
    Split("Baby Skip", FADE_BLACK),
    Split("Seaweed", DOOR_H),
    Split("Tourian Eye Door", DOOR_H),
    Split("Rinka Shaft", DOOR_H),
    Split("Mother Brain", FADE_BLACK),
    Split("Tourian Escape 1", DOOR_V),
    Split("Tourian Escape 2", DOOR_H),
    Split("Tourian Escape 3", DOOR_H),
    Split("Tourian Escape 4", DOOR_H),
    Split("Climb Spark Escape", DOOR_V),
    Split("Save The Animals", DOOR_H),
    Split("Time", VARIA_FACE)  # get a better frame


]
